language: python
python:
    - "3.4"
env:
    - 'TRAVIS_NODE_VERSION=4'
install:
    - 'node --version'
    - './setup.py develop'
    - "pip install -e '.[tests]'"
script:
    - pylama
    - py.test -vvvv --showlocals
    - npm install
    - npm run-script build
sudo: false
